import os
m_code = [
    "from flask import Flask, render_template_string",
    "import pandas as pd",
    "import random, math",
    "app = Flask(__name__)",
    "DF = pd.read_parquet('train-00000-of-00001.parquet')",
    "@app.route('/')",
    "def index():",
    "    pdf = DF.iloc[random.sample(range(len(DF)), 180)]",
    "    qs = []",
    "    for idx, r in pdf.iterrows():",
    "        c = {1:'A',2:'B',3:'C',4:'D'}.get(int(r.get('cop',1)),'A')",
    "        qs.append(f\"\"\"<div id='q-{len(qs)+1}' style='background:#fff;padding:25px;margin-bottom:20px;border:1px solid #e2e8f0;border-radius:12px;box-shadow:0 1px 3px rgba(0,0,0,0.05);'><h4 style='color:#5b21b6;font-size:0.85rem;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:10px;'>Question {len(qs)+1} of 180</h4><p style='font-weight:600;font-size:1.05rem;line-height:1.6;margin-bottom:20px;color:#1e1b4b;'>{r.get('question')}</p><div class='opts-box'><label style='display:flex;align-items:center;padding:12px;border:1px solid #cbd5e1;border-radius:8px;margin-bottom:10px;cursor:pointer;'><input type='radio' name='n{idx}' value='A' onchange='mark({len(qs)+1})'> &nbsp;<b>A:</b>&nbsp; {r.get('opa')}</label><br><label style='display:flex;align-items:center;padding:12px;border:1px solid #cbd5e1;border-radius:8px;margin-bottom:10px;cursor:pointer;'><input type='radio' name='n{idx}' value='B' onchange='mark({len(qs)+1})'> &nbsp;<b>B:</b>&nbsp; {r.get('opb')}</label><br><label style='display:flex;align-items:center;padding:12px;border:1px solid #cbd5e1;border-radius:8px;margin-bottom:10px;cursor:pointer;'><input type='radio' name='n{idx}' value='C' onchange='mark({len(qs)+1})'> &nbsp;<b>C:</b>&nbsp; {r.get('opc')}</label><br><label style='display:flex;align-items:center;padding:12px;border:1px solid #cbd5e1;border-radius:8px;margin-bottom:10px;cursor:pointer;'><input type='radio' name='n{idx}' value='D' onchange='mark({len(qs)+1})'> &nbsp;<b>D:</b>&nbsp; {r.get('opd')}</label></div><p class='ex' style='display:none;color:#16a34a;background:#f0fdf4;padding:15px;border-left:4px solid #16a34a;margin-top:15px;border-radius:4px;'><b>Correct Option: {c}</b><br><b>Rationale:</b> {r.get('exp')}</p></div>\")",
    "    grid = ''.join([f\"<div id='btn-{i}' onclick='document.getElementById(\\\"q-{i}\\\").scrollIntoView({{behavior:\\\"smooth\\\",block:\\\"center\\\"}})' style='padding:10px;background:#f1f5f9;border:1px solid #cbd5e1;text-align:center;cursor:pointer;font-weight:700;font-size:0.8rem;color:#475569;border-radius:6px;'>{i}</div>\" for i in range(1,181)])",
    "    html = f\"\"\"<!DOCTYPE html><html><head><title>Marrow Edition Simulator</title><link href='https://googleapis.com' rel='stylesheet'></head><body style='display:flex;font-family:\\\"Inter\\\",sans-serif;margin:0;height:100vh;overflow:hidden;background:#f8fafc;'><div id='box' style='flex:1;overflow-y:auto;padding:30px;max-width:850px;margin:0 auto;width:100%;'><div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:25px;border-bottom:2px solid #e2e8f0;padding-bottom:15px;'><h2 style='color:#4c1d95;font-weight:800;letter-spacing:-0.02em;'>mMARROW Elite Engine</h2><h3 id='t' style='background:#4c1d95;color:white;padding:8px 16px;border-radius:6px;font-variant-numeric:tabular-nums;'>03:30:00</h3></div><form>{''.join(qs)}<button type='button' onclick='sub()' style='width:100%;padding:16px;background:#1e1b4b;color:white;font-size:16px;font-weight:700;cursor:pointer;border:none;border-radius:8px;margin-top:20px;transition:background 0.2s;'>Finish & Grade Exam</button></form></div><div style='width:340px;border-left:1px solid #cbd5e1;padding:25px;overflow-y:auto;background:#fff;'><h3>PALETTE PROGRESS</h3><div style='display:grid;grid-template-columns:repeat(5,1fr);gap:6px;margin-top:20px;'>{grid}</div></div><script>let s=210*60;setInterval(()=>{{s--;let h=String(Math.floor(s/3600)).padStart(2,\"0\"),m=String(Math.floor((s%3600)/60)).padStart(2,\"0\"),r=String(s%60).padStart(2,\"0\");document.getElementById(\"t\").innerText=h+\":\"+m+\":\"+r;}},1000);function mark(i){{let btn=document.getElementById(\"btn-\"+i);btn.style.background=\"#f3e8ff\";btn.style.color=\"#6b21b6\";btn.style.borderColor=\"#c084fc\";}}function sub(){{document.querySelectorAll(\".ex\").forEach(p=>p.style.display=\"block\");alert(\"Marrow Sheet Submitted! Scroll down to review rationales.\");document.getElementById('box').scrollTop=0;}}</script></body></html>\"\"\"",
    "    return render_template_string(html)",
    "if __name__ == '__main__':",
    "    app.run(debug=True, port=5000)"
]
with open("app.py", "w", encoding="utf-8") as f:
    f.write("\n".join(m_code))
print("=== MARROW UPGRADE COMPLETE ===")
